sudo: false
language: cpp
compiler: clang

install:
- wget -qO - http://misc.meastman.org/openldap/openldap-2.4.40-precise-623d20db19e3f1e893fa932cd1e2c2dd.tar.bz2 | tar -C /tmp -jx

script:
- make OPENLDAP_DIR=/tmp/openldap-2.4.40/src
